### ISSUE TITLE
an error called “No such file or directory: 'two33load.npy'”

### ISSUE THREAD

**Issue by zhangdahua1** [ikelq/single-period-two-critic-DRL#1]
Hello, I found your program while studying your paper. However, some of these programs are out of line when running and lack the "two33load. npy" file. Can this document be made public? I look forward to your reply.

**Comment by ikelq** [comment]
You can generate the file in these python files. I commentted those codes. any question can contect me though wechat liuqiong_yl.










At 2023-02-02 16:45:14, "zhanghua" ***@***.***> wrote:

Hello, I found your program while studying your paper. However, some of these programs are out of line when running and lack the "two33load. npy" file. Can this document be made public? I look forward to your reply.

**Comment by zhangdahua1** [comment]
Thank you for your answer. I have found this file. Wish you a happy life！

**Comment by HafizRiaz** [comment]
zhangdahu1 would you please tell me what specific lines need to be commented to generate "two33load. npy" file as i have tried a this command
" ieee_model = pc.from_mpc('case33_bw.mat', f_hz=50, casename_mpc_file='mpc', validate_conversion=False)"
but it generated this error  "name 'pc' is not defined". Plz help me resolve this issue

**Comment by wjk2024** [comment]
请问你是如何解决"two33load. npy" file问题的？

**Comment by wjk2024** [comment]
> Thank you for your answer. I have found this file. Wish you a happy life！谢谢你的回复，我已经找到了这个文件，祝你生活愉快！

请问这个文件是哪个
