### ISSUE TITLE
Which paper this code is for?

### ISSUE THREAD

**Issue by YongtaiQ** [ikelq/single-period-two-critic-DRL#3]
亲爱的作者，我在研究Inverter-based Volt-Var Control时发现了你的程序，请问这是哪篇论文的代码？非常期待您的回复，祝你身体健康，工作顺利。

Dear author, I found your program while researching Inverter-based Volt-Var Control. Could you please tell me which paper this code is for? I look forward to your reply. Wishing you good health and success in your work.

**Comment by ikelq** [comment]
this paper

@ARTICLE{10470443,
  author={Liu, Qiong and Guo, Ye and Deng, Lirong and Liu, Haotian and Li, Dongyu and Sun, Hongbin and Huang, Wenqi},
  journal={IEEE Transactions on Sustainable Energy}, 
  title={Two-Critic Deep Reinforcement Learning for Inverter-based Volt-Var Control in Active Distribution Networks}, 
  year={2024},
  volume={},
  number={},
  pages={1-14},
  keywords={Task analysis;Reactive power;Real-time systems;Optimization;Mathematical models;Deep reinforcement learning;Vectors;Volt-Var control;deep reinforcement learning;actor-critic;active distribution network},
  doi={10.1109/TSTE.2024.3376369}}

**Comment by YongtaiQ** [comment]
Many thanks, best wish : )



---Original---
From: "Liu ***@***.***&gt;
Date: Wed, Apr 10, 2024 11:01 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ikelq/single-period-two-critic-DRL] Which paper this code isfor? (Issue #3)




 
this paper
 
@Article{10470443,
 author={Liu, Qiong and Guo, Ye and Deng, Lirong and Liu, Haotian and Li, Dongyu and Sun, Hongbin and Huang, Wenqi},
 journal={IEEE Transactions on Sustainable Energy},
 title={Two-Critic Deep Reinforcement Learning for Inverter-based Volt-Var Control in Active Distribution Networks},
 year={2024},
 volume={},
 number={},
 pages={1-14},
 keywords={Task analysis;Reactive power;Real-time systems;Optimization;Mathematical models;Deep reinforcement learning;Vectors;Volt-Var control;deep reinforcement learning;actor-critic;active distribution network},
 doi={10.1109/TSTE.2024.3376369}}
