### ISSUE TITLE
Reproduction of paper result

### ISSUE THREAD

**Issue by HafizRiaz** [ikelq/single-period-two-critic-DRL#4]
Dear Author, i am very thankful to you for providing the code base for the paper. When i run the code, it generates excel files comprising Violation sum and grid loss along with actor critic loss. Would you please let me know how to generate voltage violation rate and reward plot as per Fig. 4 (a) of the paper and additionally voltage magnitude (p.u) . Looking forward to hear a positive response from your side

**Comment by ikelq** [comment]
I have added a Jupiter notebook file as an example for plotting the simulation results

**Comment by HafizRiaz** [comment]
I appreciate your efforts and kind response.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by HafizRiaz** [comment]
> I have added a Jupiter notebook file as an example for plotting the simulation results

HI there, i have tried to explore the "Jupiter notebook file" provided by you. Actually after running TC-DDPG, TC-SAC, SAC & DDPG_and_one_step.py (as simple DDPG code file is missing in folder), i could only obtain 9 files having 3 files for each case (33,69,118) like this "traintest695550.9tc". In addition to these files, some csv files are not being generated including 'tootsa.csv' & 'two.csv'. Plz help me generating these files so that i may reproduce the paper result. lastly is 'DDPG_and_one_step.py' used to generate the results of DDPG case in figure of Reward, poer loss and voltage violation rate?

**Comment by HafizRiaz** [comment]
Dear Author, please respond to the above query, as i have tried a lot to obtain the results from jupiter notebook but could not get the plots due to unavailability of required files.. Stay blessed and have a good day

**Comment by ikelq** [comment]
In DDPG_and_one_step.py, you need to set gamma = 0.9 and 0.0 separately. The setting in "SAC" is similar.  
After you understand the code and the corresponding paper completely, you can modify those code as your desire.

**Comment by ikelq** [comment]
you can also add my wechat liuqiong_yl

**Comment by HafizRiaz** [comment]
Thanks a lot for your kind response and consideration. Have a good day. Stay blessed

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
